### ISSUE TITLE
Add Tracey job in jobDSL

### ISSUE THREAD

**Issue by sofusalbertsen** [Praqma/tracey#32]
@Andrey9kin or @MadsNielsen Is it possible that one of you can implement the tracey job in jobDSL?

**Comment by Andrey9kin** [comment]
@sofusalbertsen probably but you have to explain what you want :)

**Comment by sofusalbertsen** [comment]
Ok. 
Right now I have set up Jenkins and RabbitMQ.
I have downloaded a git repository, and made an Eiffel protocol message.
Now, I just need the included Jenkins to have a job that triggers through Tracey.
So by a script:
- insert the global configuration for the RabbitMQ broker (credential)
- setup a job that triggers on Tracey messages.

Does that make sense?

**Comment by sofusalbertsen** [comment]
Done
