### ISSUE TITLE
Jenkins does not connect to RabbitMQ after first run.

### ISSUE THREAD

**Issue by sofusalbertsen** [Praqma/tracey#33]
2nd time and onwards i run "docker-compose up" i get this message:

> jmaster_1  | Sep 05, 2016 12:03:10 PM hudson.model.AbstractProject onLoad
> jmaster_1  | WARNING: could not start trigger while loading project 'tracey-demo-scm-trigger'
> jmaster_1  | java.lang.NullPointerException
> jmaster_1  |  at org.jenkinsci.tracey.TraceyGlobalConfig.getById(TraceyGlobalConfig.java:46)
> jmaster_1  |  at org.jenkinsci.tracey.TraceyTrigger.configureBroker(TraceyTrigger.java:102)
> jmaster_1  |  at org.jenkinsci.tracey.TraceyTrigger.start(TraceyTrigger.java:69)
> jmaster_1  |  at org.jenkinsci.tracey.TraceyTrigger.start(TraceyTrigger.java:41)
> jmaster_1  |  at hudson.model.AbstractProject.onLoad(AbstractProject.java:329)
> jmaster_1  |  at hudson.model.Project.onLoad(Project.java:98)
> jmaster_1  |  at hudson.model.Items.load(Items.java:327)
> jmaster_1  |  at jenkins.model.Jenkins$18.run(Jenkins.java:2719)
> jmaster_1  |  at org.jvnet.hudson.reactor.TaskGraphBuilder$TaskImpl.run(TaskGraphBuilder.java:169)
> jmaster_1  |  at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:282)
> jmaster_1  |  at jenkins.model.Jenkins$8.runTask(Jenkins.java:925)
> jmaster_1  |  at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:210)
> jmaster_1  |  at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
> jmaster_1  |  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
> jmaster_1  |  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
> jmaster_1  |  at java.lang.Thread.run(Thread.java:745)

**Comment by sofusalbertsen** [comment]
Tried to stop jmaster and start again. Result; no solution.

**Comment by sofusalbertsen** [comment]
@MadsNielsen Do you know what causes this?

**Comment by MadsNielsen** [comment]
What happens if you save before run?

**Comment by MadsNielsen** [comment]
I'll take a look tomorrow.

**Comment by MadsNielsen** [comment]
My commit fixed the issue. Closing this.
