### ISSUE TITLE
Mock up the architecture

### ISSUE THREAD

**Issue by praqma-thi** [Praqma/tracey#4]
- [x] Mockup basic classes
- [x] Make something that can send the message using proposed architecture

**Comment by MadsNielsen** [comment]
I've Got a tracey wrapper that can send a message to 'somewhere'. Currently only implemented in the CLI.

**Comment by MadsNielsen** [comment]
I've also added a mockup trigger plugin for tracey. Located and documented here: https://github.com/Praqma/tracey-exp
